### ISSUE TITLE
repeated function are not recognised

### ISSUE THREAD

**Issue by gracjanmaciejewski** [mattpitkin/theonlinemcmc#22] opened 2019-09-04 14:35 UTC
While putting a function

a + A * sin((x-fia) * 2 * pi) + B * sin((x-fib) * 4 * pi)

second 'sin' and 'pi' are not recognised as functions and they are listed as parameters. I think there was no such problem 3 months ago.

**Comment by mattpitkin** [comment] 2019-09-04 20:26
Thanks for letting me know. I'll take a look and see if this can be fixed easily.

**Comment by mattpitkin** [comment] 2019-09-04 21:13
This has been fixed in #21, which I hadn't got round to merging. I've merged that PR and updated the website appropriately. It looks like this has fixed the problem, but let me know if it works for you now (make sure to refresh the browser window and cache).

**Comment by gracjanmaciejewski** [comment] 2019-09-06 11:26
Thanks! The web interface works fine now. 
I noticed, however, further problems: something like over 80% submissions remains without any response ("SUBMISSION SUCCESSFUL” but no email received). For that reason I have not managed to investigate deeper and confirm my finding that there could be some problems with parameter managing/counting. For instance: while fitting 
   a + A * sin((x-fia) * 2 * pi) + B * sin((x-fib) * 4 * pi)
I’ve got a solution in which A was taken as B and B as A (also priors of A were used for B and vice versa).

**Comment by mattpitkin** [comment] 2019-09-06 11:57
@gracjanmaciejewski Could you send me an example link to where it looks like the priors were swapped?

Regarding the submissions where you've not received any email, I can see three jobs from last night that seemed to fail without giving any reason. They seem to have accepted the abscissa variable data, but nothing else, so I'm not sure what the problem is. If you could let me know what inputs you used for the failed runs I might be able to figure it out.

**Comment by gracjanmaciejewski** [comment] 2019-09-06 13:52
Sure, swapped priors are here http://www.theonlinemcmc.com/results/9118725638c696aa424a61d81f6febe2/ <http://www.theonlinemcmc.com/results/9118725638c696aa424a61d81f6febe2/>
I believe, however, that the problem could be generated by my browser as described below.

As I sent dozens jobs in last 30 hours without any response and some of them seem to be incomplete (e.g. just accepted abscissa variable data), I’ve tried another browser. I used Safari 12.1.2. It looks like that browser sends form data incorrectly. I’ve switched to Chrome 76.0.3809.132 and so far so good - jobs are completed with response within a couple minutes! The  problem seems to be solved.

Please also note that there is a „display” bug in „BEST FIT VALUES & DISTRIBUTION”: Variable names and their values are mixed up at least in the first table, see for instance http://www.theonlinemcmc.com/results/fa813bc46595cebb1f5e3d83441dce6c/ <http://www.theonlinemcmc.com/results/fa813bc46595cebb1f5e3d83441dce6c/>
and compare to „MARGINALISED POSTERIORS” where chart labels and values are ok.

Here is another example - a little more complicated fit of a function
   b + Aa * sin((x-fia)*2*pi) + Ab * sin((x-fib)*4*pi)
and in BEST FIT VALUES & DISTRIBUTION of 
   http://www.theonlinemcmc.com/results/49b6cae1cedbabcdc2ce5437c585aeed <http://www.theonlinemcmc.com/results/49b6cae1cedbabcdc2ce5437c585aeed>
there are variables listed:
 b, Aa, fia, Ab, fib
but according to their values the correct order should be
 Aa, fia, b, fib, Ab
also - as it is written in columns of ‚posterior_samples.txt’.

By the way:
while increasing the "Number of MCMC iterations (default: 2000)" to 11000, I’ve got an error
http://www.theonlinemcmc.com/results/8e6621291351d996d8096018af9de94a/ <http://www.theonlinemcmc.com/results/8e6621291351d996d8096018af9de94a/>
Is there any limit on on the length of chains?

**Comment by mattpitkin** [comment] 2019-09-06 14:47
@gracjanmaciejewski thanks for this very useful feedback. I'd never tested the site on Safari and have only ever tried Chrome, but this is useful to know - I'll try to fix it for the future if I can figure out the what's going on.

> Please also note that there is a „display” bug in „BEST FIT VALUES & DISTRIBUTION”: Variable names and their values are mixed up at least in the first table, see for instance http://www.theonlinemcmc.com/results/fa813bc46595cebb1f5e3d83441dce6c/ <http://www.theonlinemcmc.com/results/fa813bc46595cebb1f5e3d83441dce6c/> and compare to „MARGINALISED POSTERIORS” where chart labels and values are ok.


I'll take a look at this and see if I can find the problem.

>  By the way:
while increasing the "Number of MCMC iterations (default: 2000)" to 11000, I’ve got an error
http://www.theonlinemcmc.com/results/8e6621291351d996d8096018af9de94a/ <http://www.theonlinemcmc.com/results/8e6621291351d996d8096018af9de94a/>
Is there any limit on on the length of chains?

I'm not sure what the problem was in this case. The sampling seems to have completed, but the plots never got produced. This must have hit some other bug in the post-processing code.

**Comment by mattpitkin** [comment] 2019-09-06 16:00
@gracjanmaciejewski I think I've broken the site for the moment. I'll try and fix things later this evening if possible.

**Comment by mattpitkin** [comment] 2019-09-06 18:55
@gracjanmaciejewski the problem

> Please also note that there is a „display” bug in „BEST FIT VALUES & DISTRIBUTION”: Variable names and their values are mixed up at least in the first table, see for instance http://www.theonlinemcmc.com/results/fa813bc46595cebb1f5e3d83441dce6c/ http://www.theonlinemcmc.com/results/fa813bc46595cebb1f5e3d83441dce6c/ and compare to „MARGINALISED POSTERIORS” where chart labels and values are ok.

should be fixed now.

**Comment by mattpitkin** [comment] 2019-09-07 17:10
I've opened a new issue (#24) about the Safari problem, but otherwise think it's ok to close this one.

**Closed as completed by mattpitkin** 2019-09-07 17:10 UTC

**Comment by gracjanmaciejewski** [comment] 2019-09-08 21:56
Thanks a lot! 

Coming back to long chains in emcee, I did some experiments to find out what is the maximal value of 'Number of ensemble points’ and 'Number of MCMC interactions’ but I have no clear picture of the problem. For instance I can run up to 
30 x (10000 - 1000) http://www.theonlinemcmc.com/results/18ec0800d213dbb64fdcb3e7f2d59950 <http://www.theonlinemcmc.com/results/18ec0800d213dbb64fdcb3e7f2d59950>
but 
40 x (10000 - 1000) http://www.theonlinemcmc.com/results/82c53a1900c9660724fa6dc0d5d0265c
fails.
That’s is not a big issue because if you need 100 chains, each of which is 10^4 step long, you can submit 4 runs (i.e. 3 x 30 chains + 1 x 10 chains). But things may get complicated for longer chains. For instance, I tried 10 x (51000 - 1000) which were fine.  But 10 x (100000 - 1000) failed without any notification (since yesterday).

**Comment by mattpitkin** [comment] 2019-09-09 13:22
@gracjanmaciejewski the server that the site if running on is a virtual machine that may not have access to much memory, so you could just be hitting that limit. Unfortunately I don't have any control over the amount of memory available.

You could also try running instead with the nested sampling algorithm dynesty, which works well.
